<?php

namespace Database\Seeders;

use App\Models\LegalPage;
use Illuminate\Database\Seeder;

class LegalPageSeeder extends Seeder
{
    public function run(): void
    {
        LegalPage::firstOrCreate(
            ['slug' => 'terms'],
            [
                'title' => 'Terms of Service',
                'description' => 'Terms of Service for the E-Landlord property management platform.',
                'content' => $this->termsContent(),
            ]
        );

        LegalPage::firstOrCreate(
            ['slug' => 'privacy'],
            [
                'title' => 'Privacy Policy',
                'description' => 'Privacy Policy for the E-Landlord property management platform.',
                'content' => $this->privacyContent(),
            ]
        );
    }

    protected function termsContent(): string
    {
        return <<<'MD'
These Terms of Service (“Terms”) govern access to and use of the E-Landlord website and property management platform (the “Service”). By creating an account or using the Service, you agree to these Terms and our [Privacy Policy](/privacy).

## 1. Who may register

Public registration is available only to landlords and property owners. By registering you represent that you are at least 18 years old and authorized to manage the properties you add to the Service.

Assistant, agent, and tenant accounts are created by a landlord (or an authorized administrator) and are not available through the public sign-up form. If you are a tenant or assistant, ask your landlord to invite you and then sign in at the login page.

## 2. Email verification

Landlord accounts must verify their email address before accessing the dashboard and other authenticated features. We send a verification link to the address you provide. You are responsible for keeping that address current and for completing verification promptly.

## 3. Accounts and security

You are responsible for activity under your account, including actions taken by assistants you create and properties you assign to them. Keep your password confidential and notify us at support@elandlord.com if you suspect unauthorized access.

## 4. Acceptable use

You agree not to:

- use the Service for unlawful, fraudulent, or misleading purposes
- upload content you do not have the right to use
- attempt to access another user’s account, data, or properties without authorization
- interfere with the operation, security, or availability of the Service
- misrepresent your role, ownership of a property, or the status of a lease or payment

## 5. Property, tenant, and payment data

Landlords remain responsible for the accuracy of property listings, lease terms, rent amounts, receipts, and tenant records entered into the Service. Digital receipts generated by E-Landlord are operational records of payments you record; they are not a substitute for legal, tax, or accounting advice.

## 6. Assistants and tenants

When you create assistant or tenant accounts, you confirm that those people have agreed to receive login credentials and that you have a legitimate reason to share their name, email, and related lease information with the Service. You must not create accounts for people without a real property-management relationship.

## 7. Service availability

We aim to keep the Service available, but we do not guarantee uninterrupted or error-free operation. Features, including renewal alerts and receipt numbering, may change as the platform evolves.

## 8. Termination

You may close your account from profile settings, subject to any records you are legally required to retain. We may suspend or terminate access if you violate these Terms, if required by law, or to protect the Service and other users.

## 9. Disclaimers and limitation of liability

The Service is provided “as is.” To the fullest extent permitted by law, E-Landlord is not liable for lost rent, missed renewals, incorrect records entered by users, or indirect or consequential damages arising from use of the platform.

## 10. Changes

We may update these Terms from time to time. The “Last updated” date at the top of this page will change when we do. Continued use of the Service after an update constitutes acceptance of the revised Terms.

## 11. Contact

Questions about these Terms can be sent to [support@elandlord.com](mailto:support@elandlord.com) or through our [contact page](/contact).
MD;
    }

    protected function privacyContent(): string
    {
        return <<<'MD'
This Privacy Policy explains how E-Landlord collects, uses, and shares information when you visit our website or use the property management platform. It should be read together with our [Terms of Service](/terms).

## 1. Information we collect

We collect information you provide directly, including:

- account details such as name, email address, phone number, role, and password
- property, unit, lease, tenant, assistant, receipt, and maintenance records you enter
- messages submitted through the contact form or in-app support
- testimonials you choose to submit for possible publication

We also collect technical information such as IP address, browser type, and pages visited, which helps us operate, secure, and improve the Service.

## 2. How we use information

We use information to:

- create and authenticate landlord, assistant, agent, and tenant accounts
- send email verification and password-reset messages
- provide dashboards, receipts, renewal alerts, and maintenance workflows
- respond to support requests
- protect the Service against abuse and unauthorized access
- meet legal obligations

## 3. Email verification and communications

When a landlord registers, we send a verification email so we can confirm the address belongs to you. We also send transactional messages needed to operate the Service, such as password resets. We do not sell your personal information.

## 4. Sharing

Property and tenant data is visible to the landlord who owns the records and to assistants or agents that landlord assigns. Tenants can see their own leases, receipts, and maintenance tickets. We may share information with infrastructure providers that host the Service, or if required by law.

## 5. Retention

We retain account and property-management records for as long as the account is active and as needed to provide the Service, resolve disputes, and comply with legal requirements. You may request deletion of your account from profile settings, subject to records a landlord must keep for other users or leases.

## 6. Security

We use reasonable administrative and technical measures to protect information, including hashed passwords and authenticated sessions. No method of transmission or storage is completely secure, so we cannot guarantee absolute security.

## 7. Cookies

The Service uses session cookies required to keep you signed in and to protect forms against cross-site request forgery. These cookies are necessary for the platform to function.

## 8. Children’s privacy

The Service is intended for adults who manage or occupy rental property. We do not knowingly collect personal information from children under 18.

## 9. Your choices

You may update your name, email, and password from your profile. Unverified landlord accounts can resend the verification email. For questions or privacy requests, contact [support@elandlord.com](mailto:support@elandlord.com).

## 10. Changes

We may update this Policy from time to time. The “Last updated” date will change when we do. Material changes will be reflected on this page.
MD;
    }
}
